// utils/country-mapper.ts
export const getCountryName = (countryCode: string): string => {
    const countryMap: Record<string, string> = {
        'DE': 'Germany',
        'FR': 'France',
        'IT': 'Italy',
        'ES': 'Spain',
        'NL': 'Netherlands',
        'BE': 'Belgium',
        'AT': 'Austria',
        'PT': 'Portugal',
        'GR': 'Greece',
        'IE': 'Ireland',
        'DK': 'Denmark',
        'SE': 'Sweden',
        'FI': 'Finland',
        'NO': 'Norway',
        'PL': 'Poland',
        'CZ': 'Czech Republic',
        'HU': 'Hungary',
        'RO': 'Romania',
        'BG': 'Bulgaria',
        'HR': 'Croatia',
        'SI': 'Slovenia',
        'SK': 'Slovakia',
        'LT': 'Lithuania',
        'LV': 'Latvia',
        'EE': 'Estonia',
        'LU': 'Luxembourg',
        'MT': 'Malta',
        'CY': 'Cyprus',
        'US': 'United States',
        'MX': 'Mexico',
        'CL': 'Chile',
        'AR': 'Argentina',
        'BR': 'Brazil',
        'CA': 'Canada',
        'AU': 'Australia',
        'NZ': 'New Zealand',
        'JP': 'Japan',
        'CN': 'China',
        'IN': 'India',
        'KR': 'South Korea',
        'ZA': 'South Africa',
        'RU': 'Russia',
        'TR': 'Turkey',
        'UK': 'United Kingdom',
        'GB': 'United Kingdom',
    };

    return countryMap[countryCode] || countryCode;
};